spring.application.name=ChaTop_Api

app.upload.dir=pictures
app.api.base-url = ${BASE_URL}

server.port=${SERVER_PORT}

jwt.secret=${JWT_SECRET}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}